### ISSUE TITLE
C-Space ISF code?

### ISSUE THREAD

**Issue by thomasweng15** [liruiw/OMG-Planner#10]
Hi, I've been looking for the C-Space ISF code but am having trouble locating it. I figured it would be somewhere in `planner.plan()` or in the PlanningScene class, but I don't think I see it there. I did see this in the config referring to ISF, but when I search for the variable it does not appear in the code: 

`cfg.obj_point_num = 800  # object points for KDTree in isf`

Can you point me to the C-Space ISF code? Thank you very much.

**Comment by liruiw** [comment]
Hi, we didn't release the ISF code for grasp optimization since the grasps are assumed to come from a curated database and use with standoff reaching.
