### ISSUE TITLE
layer

### ISSUE THREAD

**Issue by ldepn** [liruiw/OMG-Planner#15]
g++: error: /home/jnu/code/OMG-Planner/layers/build/temp.linux-x86_64-3.6/sdf_matching_loss_kernel.o: 没有那个文件或目录

$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

**Comment by liruiw** [comment]
Did you try compiling the layers with `python setup.py install` and failed? Maybe check what specific error it throws.

**Comment by ldepn** [comment]
> Did you try compiling the layers with `python setup.py install` and failed? Maybe check what specific error it throws.

yes ,

(omg) jnu@Default:~/ldp/OMG-Planner/layers$ python setup.py install
running install
running bdist_egg
running egg_info
writing omg.egg-info/PKG-INFO
writing dependency_links to omg.egg-info/dependency_links.txt
writing top-level names to omg.egg-info/top_level.txt
reading manifest file 'omg.egg-info/SOURCES.txt'
writing manifest file 'omg.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'omg_cuda' extension
Emitting ninja build file /home/jnu/ldp/OMG-Planner/layers/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.7.2
creating build/lib.linux-x86_64-3.6
g++ -pthread -shared -B /home/jnu/anaconda3/envs/omg/compiler_compat -L/home/jnu/anaconda3/envs/omg/lib -Wl,-rpath=/home/jnu/anaconda3/envs/omg/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/jnu/ldp/OMG-Planner/layers/build/temp.linux-x86_64-3.6/sdf_matching_loss_kernel.o /home/jnu/ldp/OMG-Planner/layers/build/temp.linux-x86_64-3.6/omg_layers.o -L/home/jnu/anaconda3/envs/omg/lib/python3.6/site-packages/torch/lib -L:/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-3.6/omg_cuda.cpython-36m-x86_64-linux-gnu.so
g++: error: /home/jnu/ldp/OMG-Planner/layers/build/temp.linux-x86_64-3.6/sdf_matching_loss_kernel.o: 没有那个文件或目录
error: command 'g++' failed with exit status 1

**Comment by liruiw** [comment]
I am not entirely sure about the cause. Maybe try debugging torch and cuda and re-compiling the layer.
