### ISSUE TITLE
download_data.sh: wget downloaded file cannot be unzipped

### ISSUE THREAD

**Issue by abhishek47kashyap** [liruiw/OMG-Planner#17]
On running `./download_data.sh`, I'm getting the following error:
```
Data downloaded. Starting to unzip
[data.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of data.zip or
        data.zip.zip, and cannot find data.zip.ZIP, period.
```

Weirdly enough, if I manually download `data.zip` from the link `https://drive.google.com/uc?export=download&id=1tHPAQ2aPdkp8cwtFP4gs4wdcP02jfGpH` and then `unzip -q data.zip`, the zip file gets unzipped successfully.

**Comment by liruiw** [comment]
Thanks for letting me know that. I am not sure about the cause but seems that `gdown` works.
