### ISSUE TITLE
Can I also implement the project in MacOS?

### ISSUE THREAD

**Issue by hjw-1014** [liruiw/OMG-Planner#7]
I tried to run this project in a virtual machine(ubuntu18.04), but it was slow. So I wonder if I can also run it on my PC (MacOS)?
Thanks in advance.

**Comment by liruiw** [comment]
I've only tested the code on Ubuntu and I am not very familiar with MacOS. I think if the installation (pytorch/cuda/kdl etc) can be done, it's possible to run on Mac. I am not sure how much it would speed up.
