### ISSUE TITLE
 failed_ik

### ISSUE THREAD

**Issue by Mr-Xia-6** [liruiw/OMG-Planner#8]
004_sugar_box IK init time: 0.682, failed_ik: 99, goal set num: 0/100
self.target_pos
len(target_pos)= 9
object_pose.shape= (4, 4)
self.traj.start= (8,)
anchor_seeds= (12, 9)
004_sugar_box IK init time: 0.680, failed_ik: 99, goal set num: 0/100

**Comment by liruiw** [comment]
I am not sure about the exact issues, but it could be that target object is in heavy collision due to pose errors or surround obstacles, or the object is too far so that the grasps are out of reach. You might also need to tune the anchor seeds if you are using a different robot.
