### ISSUE TITLE
layers installation "nvcc fatal   : Unsupported gpu architecture 'compute_86'"

### ISSUE THREAD

**Issue by thomasweng15** [liruiw/OMG-Planner#9]
When running `python setup.py install` for layers, I get the following error: 

`nvcc fatal   : Unsupported gpu architecture 'compute_86'`

I am running with a 3090 GPU and CUDA 11.1. Is there something I can change in the layers directory to fix this issue? Thanks for your help.

**Comment by liruiw** [comment]
I haven't seen this issue before but it looks like a CUDA version problem.

**Comment by thomasweng15** [comment]
I was able to resolve this by using CUDA 11.1 and specifying it as an env variable: `CUDA_HOME=path/to/cuda python setup.py install`.
